// SPDX-FileCopyrightText: 2026 Aditya Mehra <aix.m@outlook.com>
//
// SPDX-License-Identifier: LGPL-3.0-or-later

/**
 * @file message.h
 * @brief Data model for a single chat message within a conversation.
 *        Maps to the messages table and carries metadata for stats tracking.
 * @layer Data Access
 * @dependencies Qt6::Core, Qt6::Sql
 */

#pragma once

#include <QDateTime>
#include <QJsonObject>
#include <QString>

class QSqlRecord;

/**
 * @brief Immutable data model for a single message in a conversation.
 *
 * The `role` field must be one of: "user", "assistant", "system", "tool".
 * `contentHtml` is a pre-rendered HTML cache; generated by MarkdownConverter
 * and stored to avoid repeated re-rendering on scroll.
 *
 * The `metadata` JSON stores per-message statistics:
 * { elapsed_ms, cost_usd, input_tokens, output_tokens, provider, model, finish_reason }
 */
struct Message {
    QString id;              ///< UUID v4 primary key
    QString conversationId;  ///< References conversations.id
    QString role;            ///< "user" | "assistant" | "system" | "tool"
    QString content;         ///< Raw message text (Markdown for assistant)
    QString contentHtml;     ///< Pre-rendered HTML cache (may be empty)
    QDateTime createdAt;     ///< UTC creation timestamp
    int tokenCount = 0;      ///< Token count for this message
    QString modelUsed;       ///< Model identifier used to generate this response
    QString finishReason;    ///< "stop"|"length"|"tool_calls"|"error"|"user_interrupted"
    QJsonObject metadata;    ///< {elapsed_ms, cost_usd, input_tokens, output_tokens}
    QString agentId;         ///< References agents.id; empty for user messages and legacy
    QString memberAlias;     ///< Alias used in a group chat (schema v4+); empty in 1:1

    /**
     * @brief Schema v6+: groups all messages produced in service of a single
     *        user prompt. For a user message, equals its own id. For
     *        assistant/system rows generated in response, equals the user
     *        message's id that prompted the chain, across multiple LLM
     *        iterations (tool_call → result → re-enter → ... → final text)
     *        and across cascade dispatches in a group chat. The UI groups
     *        tool_calls per-turn-per-agent via this field.
     *        Empty / null on rows from before the v6 migration is applied
     *        (the migration backfills them).
     */
    QString turnId;

    /**
     * @brief Schema v16+: captured reasoning / thinking content for
     *        assistant rows that came from a model exposing a separate
     *        thinking channel (Ollama `message.thinking`, OpenAI
     *        `delta.reasoning` + `delta.reasoning_content`, Anthropic
     *        `thinking_delta`, Gemini `parts[*].thought == true`) or
     *        emitting `\<think\>...\</think\>` inline in content.
     *
     *        Display-only by contract: NEVER read by RequestBuilder,
     *        HistoryBudgeter, ContentSanitizer, SearchService, or any
     *        path that assembles a subsequent request.  The field is
     *        rendered by the QML message bubble's collapsible
     *        Reasoning disclosure and otherwise has no effect on
     *        model behaviour.  Surfacing it through any code path
     *        that builds context would re-leak the very pollution
     *        the sidecar exists to prevent.
     *
     *        Empty for user / system / tool rows, for assistant rows
     *        from non-reasoning models, and for assistant rows whose
     *        captured thinking was whitespace-only after trim (the
     *        trim-to-empty discard rule kills false disclosures).
     */
    QString thinkingContent;

    /**
     * @brief Serializes this message to a JSON object.
     * @return QJsonObject with all fields; timestamps as Unix ms.
     */
    QJsonObject toJson() const;

    /**
     * @brief Deserializes a message from a JSON object.
     * @param json JSON object with message fields.
     * @return Populated Message struct.
     */
    static Message fromJson(const QJsonObject& json);

    /**
     * @brief Constructs a Message from a QSqlRecord row.
     * @param record SQL record from SELECT on the messages table.
     * @return Populated Message struct.
     */
    static Message fromSqlRecord(const QSqlRecord& record);

    /**
     * @brief Returns true if this message has a valid ID and role.
     * @return true if id is non-empty and role is a known value.
     */
    bool isValid() const;
};
